TARGET = XC-3
BASE_DIR = ..

DEMO_SOURCE_DIRS = . \
               buffers/ledbuffer \
               buffers/pktbuffer \
               ethernet/dualmii \
               ethernet/localServer \
               ethernet/switch \
							 ethernet \
               led/driver \
               led/ledprocess \
               support/gamma_lut_builder \
               support/misc \
               support/retrieveMAC \
               support/spiflash \
               support/watchdog

SOURCE_DIRS += $(DEMO_SOURCE_DIRS)

INCLUDE_DIRS += $(DEMO_SOURCE_DIRS)

XCC_FLAGS += -O3 -g -report -Xcompiler-xc -fxta-info

include $(BASE_DIR)/build/common/Makefile.common


all:  $(BIN_DIR)/LedRefDesign.xe
	$(XOBJDUMP) --strip $(BIN_DIR)/LedRefDesign.xe

clean: clean_common
